FROM python:3.10-slim

WORKDIR /app

# Instala bibliotecas do sistema necessárias para o OpenCV (cv2)
RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

# Copia e instala dependências Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia o restante do código da aplicação
COPY . .

# Comando para rodar o worker
CMD ["python", "run_worker.py"]
